name: .NET

on:
  push:
    tags: 
      - '*'

jobs:
  backend:
    runs-on: ubuntu-latest
    needs: [moveFrontend]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/HolePunch.Web
    - name: Download frontend dist
      uses: actions/download-artifact@v2
      with:
        name: frontend-dist
    - name: Move frontend dist to wwwroot
      run: mv ./src/ng-holepunch/dist/ng-holepunch ./src/HolePunch.Web/wwwroot
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/HolePunch.Web
      
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm i
      working-directory: ./src/ng-holepunch
    - name: Build
      run: npm run build
      working-directory: ./src/ng-holepunch
    - name: Upload dist for backend
      uses: actions/upload-artifact@v2
      with:
        name: frontend-dist
        path: ./src/ng-holepunch/dist/ng-holepunch
