name: .NET

on:
  push:
    tags: 
      - '*'

jobs:
  backend:
    runs-on: ubuntu-latest
    needs: [frontend]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/HolePunch.Web
    - name: Download frontend dist
      uses: actions/download-artifact@v2
      with:
        name: wwwroot
        path: ./src/HolePunch.Web/wwwroot 
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./src/HolePunch.Web/Dockerfile
        context: ./src
        push: true
        tags: xupeiyao/holepunchweb:latest,xupeiyao/holepunchweb:${{steps.tag.outputs.tag}}
      
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm i
      working-directory: ./src/ng-holepunch
    - name: Build
      run: npm run build
      working-directory: ./src/ng-holepunch
    - name: Upload dist for backend
      uses: actions/upload-artifact@v2
      with:
        name: wwwroot
        path: ./src/ng-holepunch/dist/ng-holepunch
