name: .NET

on:
  push:
    tags: 
      - '*'

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/HolePunch.Web
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
